name: Create Jira Issue

on:
  push:
    paths:
      - 'user_stories.md'  # Adjust path to your user story file

jobs:
  create-jira-issue:
    runs-on: windows
    steps:
      - name: Requiremnts
        uses: actions/checkout@v2

      - name: Create Jira Issue
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          USER_STORY=$(cat path/to/user_stories/C:\Users\MY HP\Desktop\GitHub_Requirements\GroupBillPaymentUserStories\user_stories.md)  # Adjust the path
          curl -X POST -H "Content-Type: application/json" \
            -u "$JIRA_USER:$JIRA_API_TOKEN" \
            -d '{
                  "fields": {
                    "project": {
                      "key": "SEISER"
                    },
                    "summary": "'"${USER_STORY}"'",
                    "description": "Created from GitHub.",
                    "issuetype": {
                      "name": "User Story"
                    }
                  }
                }' \
            "$JIRA_URL/rest/api/3/issue"
