name: Create Jira Issue

on:
  push:
    paths:
      - 'user_stories/**'  # Adjust path to your user story files

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Jira Issue
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          USER_STORY=$(cat user_stories/user_stories.md)  # Read the user story file (adjust as needed)

          curl -X POST -H "Content-Type: application/json" \
            -u "$JIRA_USER:$JIRA_API_TOKEN" \
            -d '{
                  "fields": {
                    "project": {
                      "key": "YOUR_PROJECT_KEY"  # Replace with your actual project key
                    },
                    "summary": "'"${SEISER}"'",  # The title of the Jira issue
                    "description": "Created from GitHub.",  # Additional description
                    "issuetype": {
                      "name": "Story"  # Adjust based on your Jira configuration
                    }
                  }
                }' \
            "$JIRA_URL/rest/api/3/issue"

